# Site settings
title: Prostendo
email: martijn.simon.bakker@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some description. pretty nifty this jekyll stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gladdy.github.io" # the base hostname & protocol for your site

name: Martijn Bakker
twitter_username: jekyllrb
github_username:  gladdy
facebook_username: martijn.bakker.737
linkedin_link: martijn-bakker/93/462/731

# Build settings
markdown: kramdown
